# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x04test\"\xee\x01\n\x07Weather\x12\x14\n\ttimestamp\x18\x01 \x01(\x05:\x01\x30\x12!\n\x11temp_centicelsius\x18\x02 \x01(\x05:\x06-27315\x12\x13\n\x08pres_hpa\x18\x03 \x01(\x05:\x01\x30\x12\x31\n\ndescriptor\x18\x04 \x01(\x0e\x32\x18.test.Weather.Descriptor:\x03SUN\"b\n\nDescriptor\x12\x07\n\x03SUN\x10\x00\x12\t\n\x05\x43LOUD\x10\x01\x12\x08\n\x04RAIN\x10\x02\x12\x0b\n\x07THUNDER\x10\x03\x12\x08\n\x04SNOW\x10\x04\x12\x08\n\x04HAIL\x10\x05\x12\x15\n\x11INDESCRIBABLY_BAD\x10\x06')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEATHER._serialized_start=24
  _WEATHER._serialized_end=262
  _WEATHER_DESCRIPTOR._serialized_start=164
  _WEATHER_DESCRIPTOR._serialized_end=262
# @@protoc_insertion_point(module_scope)
